- host: host1
  login:
    user: user1
    password: pass1
  services:
    - vmtoolsd
  check_disk_usage: true

- host: host2
  login:
    user: user2
    password: pass2
  services:
    - ntpd
  check_disk_usage: true